version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    container_name: elasticsearch
    env_file:
      - ./.env
    environment:
      - ELASTIC_PASSWORD=$ES_PASSWORD
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - 9200:9200
    networks:
      - esnet
    volumes:
      - db:/usr/share/elasticsearch/data
  mysqldb:
    image: mysql:latest
    container_name: mysql
    env_file:
      - ./.env
    networks:
      - esnet
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=$MYSQL_DB
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
    volumes:
      - db:/var/lib/mysql
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - esnet
    env_file:
      - ./.env
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - db:/data
  api:
    image: node:latest
    container_name: node
    build: .
    restart: on-failure:10
    ports:
      - 3000:3000
    networks:
      - esnet
    env_file:
      - ./.env
    environment:
      - MYSQL_HOST=mysqldb
      - REDIS_HOST=redis
      - ES_URL=http://elasticsearch:9200
    depends_on:
      - mysqldb
      - elasticsearch
      - redis
    volumes:
      - ./:/app
networks:
  esnet:
volumes:
  db: